### ISSUE TITLE
sync_view() not working

### ISSUE THREAD

**Issue by gbayarri** [arose/nglview#814]
According to the README file, the correct way to synchronize two views showed in a HBox should be like that:

![scr](https://user-images.githubusercontent.com/19928100/58811441-1ae80700-8620-11e9-93cd-14b444500a52.png)

But it doesn't work. Am I missing something? Is there some complete example of this feature?
Thanks.

**Comment by hainm** [comment]
hi sorry for the confusion, 'sync_view` has different meaning here. Saying you have a "view" and you want to display twice (not two different "view" in your case), two views should be the same orientation. However, this feature does not work well and we will remove it from README.

>  Is there some complete example of this feature?

Due to technical issue, the sync of two different views are not supported (yet).

**Comment by gbayarri** [comment]
Ok, thanks for your fast answer.

**Comment by hainm** [comment]
@gbayarri you can set one way sync like below:;

```
# cell 1
import nglview as nv
from ipywidgets import HBox

v0 = nv.show_pdbid('1l2y')
v1 = nv.show_pdbid('1tsu')

v0._set_size('500px', '')
v1._set_size('500px', '')

HBox([v0, v1])

# cell 2
def on_change(change):
    v1._set_camera_orientation(change['new'])
    
v0.observe(on_change, ['_camera_orientation'])
```

**Comment by gbayarri** [comment]
That will do the trick, @hainm 

Thanks!

**Comment by hainm** [comment]
hi @gbayarri, you now can sync camera of a `view` that is displayed multiple times.
Please check v2.2.0 (https://github.com/arose/nglview/pull/826)

**Comment by gbayarri** [comment]
Thanks @hainm , it works perfectly!
